-- Creating the 'review' table structure
CREATE TABLE IF NOT EXISTS public.review (
    review_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    inv_id INTEGER NOT NULL,
    account_id INTEGER NOT NULL,
    review_text TEXT NOT NULL,
    review_rating INTEGER NOT NULL,
    review_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT review_pkey PRIMARY KEY (review_id),
    CONSTRAINT fk_inventory FOREIGN KEY (inv_id)
        REFERENCES public.inventory (inv_id)
        MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_account FOREIGN KEY (account_id)
        REFERENCES public.account (account_id)
        MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT check_rating CHECK (review_rating >= 1 AND review_rating <= 5)
);